export const symptoms = [
  {
    id: 1,
    name: "Vomiting",
    category: "digestive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "guinea_pig",
      "hamster",
    ],
  },
  {
    id: 2,
    name: "Diarrhea",
    category: "digestive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 3,
    name: "Loss of appetite",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 4,
    name: "Lethargy",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 5,
    name: "Difficulty breathing",
    category: "respiratory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 6,
    name: "Coughing",
    category: "respiratory",
    severity: "medium",
    applicable_animals: ["dog", "cat", "cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 7,
    name: "Sneezing",
    category: "respiratory",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 8,
    name: "Excessive scratching",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 9,
    name: "Hair loss",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
    ],
  },
  {
    id: 10,
    name: "Skin rash",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 11,
    name: "Limping",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 12,
    name: "Swollen joints",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: ["dog", "cat", "cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 13,
    name: "Seizures",
    category: "neurological",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 14,
    name: "Excessive thirst",
    category: "metabolic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 15,
    name: "Frequent urination",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 16,
    name: "Blood in urine",
    category: "urinary",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 17,
    name: "Eye discharge",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 18,
    name: "Red eyes",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 19,
    name: "Cloudy eyes",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 20,
    name: "Ear discharge",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 21,
    name: "Head shaking",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 22,
    name: "Bad breath",
    category: "dental",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 23,
    name: "Difficulty eating",
    category: "dental",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 24,
    name: "Drooling",
    category: "dental",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 25,
    name: "Swollen abdomen",
    category: "digestive",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 26,
    name: "Constipation",
    category: "digestive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 27,
    name: "Weight loss",
    category: "metabolic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 28,
    name: "Weight gain",
    category: "metabolic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 29,
    name: "Fever",
    category: "systemic",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 30,
    name: "Pale gums",
    category: "circulatory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 31,
    name: "Rapid heartbeat",
    category: "circulatory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 32,
    name: "Weakness",
    category: "muscular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 33,
    name: "Trembling",
    category: "neurological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 34,
    name: "Difficulty walking",
    category: "musculoskeletal",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 35,
    name: "Excessive panting",
    category: "respiratory",
    severity: "medium",
    applicable_animals: ["dog", "cat", "cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 36,
    name: "Nasal discharge",
    category: "respiratory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 37,
    name: "Swollen lymph nodes",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 38,
    name: "Excessive vocalization",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 39,
    name: "Hiding behavior",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
    ],
  },
  {
    id: 40,
    name: "Aggression",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 41,
    name: "Restlessness",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 42,
    name: "Changes in sleep pattern",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
    ],
  },
  {
    id: 43,
    name: "Lumps or bumps",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 44,
    name: "Open wounds",
    category: "dermatological",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 45,
    name: "Swelling",
    category: "inflammatory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 46,
    name: "Jaundice (yellow skin/eyes)",
    category: "hepatic",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 47,
    name: "Dark urine",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 48,
    name: "Straining to urinate",
    category: "urinary",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 49,
    name: "Blood in stool",
    category: "digestive",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 50,
    name: "Difficulty swallowing",
    category: "digestive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 51,
    name: "Regurgitation",
    category: "digestive",
    severity: "medium",
    applicable_animals: ["dog", "cat", "bird", "ferret"],
  },
  {
    id: 52,
    name: "Excessive salivation",
    category: "digestive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 53,
    name: "Grinding teeth",
    category: "dental",
    severity: "medium",
    applicable_animals: [
      "rabbit",
      "guinea_pig",
      "hamster",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 54,
    name: "Broken teeth",
    category: "dental",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 55,
    name: "Yellow teeth",
    category: "dental",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 56,
    name: "Loose teeth",
    category: "dental",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 57,
    name: "Tartar buildup",
    category: "dental",
    severity: "low",
    applicable_animals: ["dog", "cat", "ferret"],
  },
  {
    id: 58,
    name: "Wheezing",
    category: "respiratory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 59,
    name: "Rapid breathing",
    category: "respiratory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 60,
    name: "Shallow breathing",
    category: "respiratory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 61,
    name: "Blue gums/tongue",
    category: "respiratory",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 62,
    name: "Open mouth breathing",
    category: "respiratory",
    severity: "high",
    applicable_animals: [
      "cat",
      "bird",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 63,
    name: "Irregular heartbeat",
    category: "cardiac",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 64,
    name: "Slow heartbeat",
    category: "cardiac",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 65,
    name: "Heart murmur",
    category: "cardiac",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 66,
    name: "Swollen legs/feet",
    category: "cardiac",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 67,
    name: "Exercise intolerance",
    category: "cardiac",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 68,
    name: "Paralysis",
    category: "neurological",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 69,
    name: "Loss of coordination",
    category: "neurological",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 70,
    name: "Head tilt",
    category: "neurological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
  },
  {
    id: 71,
    name: "Circling behavior",
    category: "neurological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 72,
    name: "Blindness",
    category: "neurological",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 73,
    name: "Muscle twitching",
    category: "neurological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 74,
    name: "Abnormal posture",
    category: "neurological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 75,
    name: "Muscle stiffness",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 76,
    name: "Muscle wasting",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 77,
    name: "Back pain",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 78,
    name: "Neck pain",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 79,
    name: "Reluctance to move",
    category: "musculoskeletal",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 80,
    name: "Squinting",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 81,
    name: "Bulging eyes",
    category: "ocular",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
  },
  {
    id: 82,
    name: "Sunken eyes",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 83,
    name: "Pupils different sizes",
    category: "ocular",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 84,
    name: "Light sensitivity",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 85,
    name: "Third eyelid showing",
    category: "ocular",
    severity: "medium",
    applicable_animals: ["dog", "cat", "bird"],
  },
  {
    id: 86,
    name: "Bumping into objects",
    category: "ocular",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 87,
    name: "Ear odor",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 88,
    name: "Ear swelling",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 89,
    name: "Balance problems",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
  },
  {
    id: 90,
    name: "Tilting head frequently",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 91,
    name: "Deafness",
    category: "aural",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 92,
    name: "Dry skin",
    category: "dermatological",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 93,
    name: "Oily skin",
    category: "dermatological",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 94,
    name: "Scaly skin",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 95,
    name: "Crusty skin",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 96,
    name: "Hot spots",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 97,
    name: "Discolored skin",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 98,
    name: "Thickened skin",
    category: "dermatological",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 99,
    name: "Excessive licking",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 100,
    name: "Pacing",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 101,
    name: "Excessive barking/meowing",
    category: "behavioral",
    severity: "low",
    applicable_animals: ["dog", "cat"],
  },
  {
    id: 102,
    name: "House soiling",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 103,
    name: "Destructive behavior",
    category: "behavioral",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
  },
  {
    id: 104,
    name: "Separation anxiety",
    category: "behavioral",
    severity: "medium",
    applicable_animals: ["dog", "cat", "bird"],
  },
  {
    id: 105,
    name: "Compulsive behaviors",
    category: "behavioral",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
  },
  {
    id: 106,
    name: "Inability to urinate",
    category: "urinary",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 107,
    name: "Painful urination",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 108,
    name: "Cloudy urine",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 109,
    name: "Strong urine odor",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 110,
    name: "Dribbling urine",
    category: "urinary",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 111,
    name: "Breeding difficulties",
    category: "reproductive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 112,
    name: "Irregular heat cycles",
    category: "reproductive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 113,
    name: "Milk production problems",
    category: "reproductive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 114,
    name: "Prolonged labor",
    category: "reproductive",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 115,
    name: "Abnormal discharge",
    category: "reproductive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 116,
    name: "Cold extremities",
    category: "circulatory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 117,
    name: "Purple gums",
    category: "circulatory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 118,
    name: "Slow capillary refill",
    category: "circulatory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 119,
    name: "Weak pulse",
    category: "circulatory",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 120,
    name: "Bruising easily",
    category: "circulatory",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 121,
    name: "Enlarged liver",
    category: "hepatic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 122,
    name: "Ascites (fluid in abdomen)",
    category: "hepatic",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 123,
    name: "Clay-colored stool",
    category: "hepatic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 124,
    name: "Abdominal pain",
    category: "hepatic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 125,
    name: "Nausea",
    category: "hepatic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 126,
    name: "Frequent infections",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 127,
    name: "Slow wound healing",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 128,
    name: "Autoimmune reactions",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 129,
    name: "Allergic reactions",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 130,
    name: "Chronic fatigue",
    category: "immune",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 131,
    name: "Hormone imbalance symptoms",
    category: "endocrine",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 132,
    name: "Growth abnormalities",
    category: "endocrine",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 133,
    name: "Temperature regulation issues",
    category: "endocrine",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 134,
    name: "Metabolic changes",
    category: "endocrine",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 135,
    name: "Coat changes",
    category: "endocrine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 136,
    name: "Cancerous growths",
    category: "oncology",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 137,
    name: "Benign tumors",
    category: "oncology",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 138,
    name: "Unexplained masses",
    category: "oncology",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 139,
    name: "Rapid tumor growth",
    category: "oncology",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 140,
    name: "Bleeding tumors",
    category: "oncology",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 141,
    name: "Lameness in multiple legs",
    category: "orthopedic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 142,
    name: "Joint deformity",
    category: "orthopedic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 143,
    name: "Bone fractures",
    category: "orthopedic",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 144,
    name: "Spinal problems",
    category: "orthopedic",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 145,
    name: "Range of motion loss",
    category: "orthopedic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 146,
    name: "Nutritional deficiencies",
    category: "nutritional",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 147,
    name: "Poor body condition",
    category: "nutritional",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 148,
    name: "Stunted growth",
    category: "nutritional",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 149,
    name: "Brittle bones",
    category: "nutritional",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 150,
    name: "Vitamin deficiency symptoms",
    category: "nutritional",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 151,
    name: "Chronic pain",
    category: "pain_management",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 152,
    name: "Acute pain",
    category: "pain_management",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 153,
    name: "Pain sensitivity",
    category: "pain_management",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 154,
    name: "Phantom limb pain",
    category: "pain_management",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 155,
    name: "Post-surgical pain",
    category: "pain_management",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 156,
    name: "Surgical complications",
    category: "surgery",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 157,
    name: "Anesthesia reactions",
    category: "surgery",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 158,
    name: "Wound dehiscence",
    category: "surgery",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 159,
    name: "Post-op infection",
    category: "surgery",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 160,
    name: "Delayed healing",
    category: "surgery",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 161,
    name: "Emergency trauma",
    category: "emergency",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 162,
    name: "Poisoning symptoms",
    category: "emergency",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 163,
    name: "Shock symptoms",
    category: "emergency",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 164,
    name: "Heat stroke",
    category: "emergency",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 165,
    name: "Hypothermia",
    category: "emergency",
    severity: "critical",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 166,
    name: "Exotic disease symptoms",
    category: "exotic",
    severity: "medium",
    applicable_animals: ["bird", "reptile", "guinea_pig", "hamster", "ferret"],
  },
  {
    id: 167,
    name: "Species-specific behaviors",
    category: "exotic",
    severity: "low",
    applicable_animals: ["bird", "reptile", "guinea_pig", "hamster", "ferret"],
  },
  {
    id: 168,
    name: "Hibernation problems",
    category: "exotic",
    severity: "medium",
    applicable_animals: ["reptile", "hamster"],
  },
  {
    id: 169,
    name: "Molting issues",
    category: "exotic",
    severity: "medium",
    applicable_animals: ["bird", "reptile"],
  },
  {
    id: 170,
    name: "Environmental stress",
    category: "exotic",
    severity: "medium",
    applicable_animals: ["bird", "reptile", "guinea_pig", "hamster", "ferret"],
  },
  {
    id: 171,
    name: "Birthing complications",
    category: "obstetrics",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 172,
    name: "Pregnancy complications",
    category: "obstetrics",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 173,
    name: "Retained placenta",
    category: "obstetrics",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 174,
    name: "Maternal rejection",
    category: "obstetrics",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 175,
    name: "Neonatal problems",
    category: "obstetrics",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 176,
    name: "Geriatric weakness",
    category: "geriatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 177,
    name: "Cognitive decline",
    category: "geriatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
  },
  {
    id: 178,
    name: "Age-related arthritis",
    category: "geriatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 179,
    name: "Senior mobility issues",
    category: "geriatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 180,
    name: "Age-related organ failure",
    category: "geriatric",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 181,
    name: "Juvenile growth problems",
    category: "pediatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 182,
    name: "Developmental delays",
    category: "pediatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 183,
    name: "Failure to thrive",
    category: "pediatric",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 184,
    name: "Congenital defects",
    category: "pediatric",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 185,
    name: "Weaning problems",
    category: "pediatric",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 186,
    name: "Infectious disease symptoms",
    category: "infectious_disease",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 187,
    name: "Viral infection signs",
    category: "infectious_disease",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 188,
    name: "Bacterial infection signs",
    category: "infectious_disease",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 189,
    name: "Fungal infection signs",
    category: "infectious_disease",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 190,
    name: "Quarantine requirements",
    category: "infectious_disease",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 191,
    name: "Vaccination reactions",
    category: "preventive",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 192,
    name: "Parasite prevention needs",
    category: "preventive",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 193,
    name: "Wellness exam findings",
    category: "preventive",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 194,
    name: "Health screening results",
    category: "preventive",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 195,
    name: "Routine health maintenance",
    category: "preventive",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 196,
    name: "Diagnostic imaging needs",
    category: "diagnostic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 197,
    name: "Laboratory test abnormalities",
    category: "diagnostic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 198,
    name: "Biopsy requirements",
    category: "diagnostic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 199,
    name: "Advanced imaging needs",
    category: "diagnostic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 200,
    name: "Specialized testing required",
    category: "diagnostic",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 201,
    name: "Medication side effects",
    category: "pharmacology",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 202,
    name: "Drug interactions",
    category: "pharmacology",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 203,
    name: "Treatment resistance",
    category: "pharmacology",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 204,
    name: "Dosage adjustment needs",
    category: "pharmacology",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 205,
    name: "Alternative therapy needs",
    category: "pharmacology",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 206,
    name: "Rehabilitation needs",
    category: "rehabilitation",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 207,
    name: "Physical therapy requirements",
    category: "rehabilitation",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 208,
    name: "Mobility assistance needs",
    category: "rehabilitation",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 209,
    name: "Recovery monitoring",
    category: "rehabilitation",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 210,
    name: "Adaptive equipment needs",
    category: "rehabilitation",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 211,
    name: "Chronic disease management",
    category: "chronic_care",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 212,
    name: "Long-term care planning",
    category: "chronic_care",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 213,
    name: "Quality of life assessment",
    category: "chronic_care",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 214,
    name: "Palliative care needs",
    category: "chronic_care",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 215,
    name: "End-of-life decisions",
    category: "chronic_care",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 216,
    name: "Genetic abnormalities",
    category: "genetics",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 217,
    name: "Hereditary conditions",
    category: "genetics",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 218,
    name: "Breeding soundness issues",
    category: "genetics",
    severity: "medium",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 219,
    name: "Chromosomal disorders",
    category: "genetics",
    severity: "high",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 220,
    name: "Genetic testing needs",
    category: "genetics",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 221,
    name: "Herd health problems",
    category: "herd_health",
    severity: "medium",
    applicable_animals: ["cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 222,
    name: "Production efficiency issues",
    category: "herd_health",
    severity: "medium",
    applicable_animals: ["cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 223,
    name: "Feed efficiency problems",
    category: "herd_health",
    severity: "medium",
    applicable_animals: ["cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 224,
    name: "Environmental health concerns",
    category: "herd_health",
    severity: "medium",
    applicable_animals: ["cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 225,
    name: "Biosecurity breaches",
    category: "herd_health",
    severity: "high",
    applicable_animals: ["cow", "goat", "sheep", "horse", "pig"],
  },
  {
    id: 226,
    name: "Aquatic health issues",
    category: "aquatic",
    severity: "medium",
    applicable_animals: ["fish"],
  },
  {
    id: 227,
    name: "Water quality problems",
    category: "aquatic",
    severity: "high",
    applicable_animals: ["fish"],
  },
  {
    id: 228,
    name: "Fish behavior changes",
    category: "aquatic",
    severity: "medium",
    applicable_animals: ["fish"],
  },
  {
    id: 229,
    name: "Gill problems",
    category: "aquatic",
    severity: "high",
    applicable_animals: ["fish"],
  },
  {
    id: 230,
    name: "Swimming abnormalities",
    category: "aquatic",
    severity: "medium",
    applicable_animals: ["fish"],
  },
  {
    id: 231,
    name: "Alternative medicine needs",
    category: "alternative",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 232,
    name: "Acupuncture requirements",
    category: "alternative",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 233,
    name: "Herbal therapy needs",
    category: "alternative",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 234,
    name: "Chiropractic needs",
    category: "alternative",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 235,
    name: "Holistic treatment options",
    category: "alternative",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 236,
    name: "Telemedicine consultation needs",
    category: "telemedicine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 237,
    name: "Remote monitoring requirements",
    category: "telemedicine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 238,
    name: "Virtual follow-up needs",
    category: "telemedicine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 239,
    name: "Digital health monitoring",
    category: "telemedicine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 240,
    name: "Home care guidance needed",
    category: "telemedicine",
    severity: "low",
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
  },
  {
    id: 241,
    name: "Wildlife injury",
    category: "wildlife",
    severity: "high",
    applicable_animals: ["bird", "reptile", "wild_mammals"],
  },
  {
    id: 242,
    name: "Conservation health issues",
    category: "wildlife",
    severity: "medium",
    applicable_animals: ["bird", "reptile", "wild_mammals"],
  },
  {
    id: 243,
    name: "Habitat-related illness",
    category: "wildlife",
    severity: "medium",
    applicable_animals: ["bird", "reptile", "wild_mammals"],
  },
  {
    id: 244,
    name: "Human-wildlife conflict injuries",
    category: "wildlife",
    severity: "high",
    applicable_animals: ["bird", "reptile", "wild_mammals"],
  },
  {
    id: 245,
    name: "Species reintroduction health",
    category: "wildlife",
    severity: "medium",
    applicable_animals: ["bird", "reptile", "wild_mammals"],
  },
  {
    id: 246,
    name: "Zoo animal health issues",
    category: "zoo",
    severity: "medium",
    applicable_animals: ["exotic_mammals", "bird", "reptile", "amphibians"],
  },
  {
    id: 247,
    name: "Captive breeding problems",
    category: "zoo",
    severity: "medium",
    applicable_animals: ["exotic_mammals", "bird", "reptile", "amphibians"],
  },
  {
    id: 248,
    name: "Enrichment-related issues",
    category: "zoo",
    severity: "low",
    applicable_animals: ["exotic_mammals", "bird", "reptile", "amphibians"],
  },
  {
    id: 249,
    name: "Exhibit design health impacts",
    category: "zoo",
    severity: "medium",
    applicable_animals: ["exotic_mammals", "bird", "reptile", "amphibians"],
  },
  {
    id: 250,
    name: "Visitor interaction stress",
    category: "zoo",
    severity: "low",
    applicable_animals: ["exotic_mammals", "bird", "reptile", "amphibians"],
  },
];

export const diseases = [
  {
    id: 1,
    name: "Rabies",
    category: "viral",
    severity: "critical",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [13, 29, 40, 23],
  },
  {
    id: 2,
    name: "Distemper",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["dog", "ferret"],
    common_symptoms: [5, 6, 17, 29, 13],
  },
  {
    id: 3,
    name: "Parvovirus",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["dog"],
    common_symptoms: [1, 2, 3, 4, 29],
  },
  {
    id: 4,
    name: "Feline Leukemia",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [3, 4, 27, 29, 30],
  },
  {
    id: 5,
    name: "Feline Immunodeficiency Virus",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [3, 4, 27, 29, 37],
  },
  {
    id: 6,
    name: "Hip Dysplasia",
    category: "genetic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [11, 34, 32],
  },
  {
    id: 7,
    name: "Diabetes Mellitus",
    category: "metabolic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [14, 15, 27, 3, 4],
  },
  {
    id: 8,
    name: "Kidney Disease",
    category: "renal",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [14, 15, 3, 27, 1],
  },
  {
    id: 9,
    name: "Heart Disease",
    category: "cardiac",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [5, 35, 4, 32, 6],
  },
  {
    id: 10,
    name: "Arthritis",
    category: "inflammatory",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [11, 12, 32, 34, 41],
  },
  {
    id: 11,
    name: "Skin Allergies",
    category: "allergic",
    severity: "low",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [8, 9, 10, 43],
  },
  {
    id: 12,
    name: "Ear Infection",
    category: "bacterial",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [20, 21, 8],
  },
  {
    id: 13,
    name: "Upper Respiratory Infection",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
    ],
    common_symptoms: [7, 36, 17, 6, 29],
  },
  {
    id: 14,
    name: "Urinary Tract Infection",
    category: "bacterial",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [15, 48, 16, 47],
  },
  {
    id: 15,
    name: "Gastroenteritis",
    category: "digestive",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [1, 2, 3, 25, 29],
  },
  {
    id: 16,
    name: "Dental Disease",
    category: "dental",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
    common_symptoms: [22, 23, 24, 3],
  },
  {
    id: 17,
    name: "Obesity",
    category: "metabolic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [28, 4, 5, 34],
  },
  {
    id: 18,
    name: "Cancer",
    category: "neoplastic",
    severity: "critical",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [27, 3, 4, 43, 45],
  },
  {
    id: 19,
    name: "Parasitic Infestation",
    category: "parasitic",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [2, 1, 27, 8, 25],
  },
  {
    id: 20,
    name: "Liver Disease",
    category: "hepatic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [46, 3, 4, 1, 25],
  },
  {
    id: 21,
    name: "Pneumonia",
    category: "respiratory",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [5, 6, 29, 4, 36],
  },
  {
    id: 22,
    name: "Epilepsy",
    category: "neurological",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "rabbit", "ferret"],
    common_symptoms: [13, 33, 39, 42],
  },
  {
    id: 23,
    name: "Bloat (GDV)",
    category: "digestive",
    severity: "critical",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cow", "goat", "sheep", "horse"],
    common_symptoms: [25, 41, 5, 35, 32],
  },
  {
    id: 24,
    name: "Cataracts",
    category: "ocular",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [19, 34],
  },
  {
    id: 25,
    name: "Glaucoma",
    category: "ocular",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [18, 19, 17],
  },
  {
    id: 26,
    name: "Hypothyroidism",
    category: "endocrine",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "cow", "goat", "sheep", "horse", "pig"],
    common_symptoms: [28, 9, 4, 32],
  },
  {
    id: 27,
    name: "Hyperthyroidism",
    category: "endocrine",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["cat", "cow", "goat", "sheep", "horse", "pig"],
    common_symptoms: [27, 31, 41, 14, 15],
  },
  {
    id: 28,
    name: "Mastitis",
    category: "bacterial",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "cow", "goat", "sheep", "pig"],
    common_symptoms: [45, 29, 43, 44],
  },
  {
    id: 29,
    name: "Foot and Mouth Disease",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["cow", "goat", "sheep", "pig"],
    common_symptoms: [29, 44, 11, 24, 3],
  },
  {
    id: 30,
    name: "Laminitis",
    category: "inflammatory",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["horse", "cow", "goat", "sheep"],
    common_symptoms: [11, 34, 41, 35],
  },
  {
    id: 31,
    name: "Colic",
    category: "digestive",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["horse", "rabbit", "guinea_pig"],
    common_symptoms: [25, 41, 35, 38, 3],
  },
  {
    id: 32,
    name: "Scours",
    category: "digestive",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cow", "goat", "sheep", "pig"],
    common_symptoms: [2, 3, 4, 32],
  },
  {
    id: 33,
    name: "Milk Fever",
    category: "metabolic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["cow", "goat", "sheep"],
    common_symptoms: [32, 33, 34, 13],
  },
  {
    id: 34,
    name: "Respiratory Disease Complex",
    category: "respiratory",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cow", "goat", "sheep", "pig"],
    common_symptoms: [6, 36, 29, 5, 4],
  },
  {
    id: 35,
    name: "Worms (Intestinal Parasites)",
    category: "parasitic",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [2, 1, 27, 25, 3],
  },
  {
    id: 36,
    name: "Fleas",
    category: "parasitic",
    severity: "low",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
    common_symptoms: [8, 9, 10],
  },
  {
    id: 37,
    name: "Ticks",
    category: "parasitic",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [8, 29, 4, 37],
  },
  {
    id: 38,
    name: "Mange (Mites)",
    category: "parasitic",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [8, 9, 10, 43],
  },
  {
    id: 39,
    name: "Ringworm",
    category: "fungal",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [9, 10, 8],
  },
  {
    id: 40,
    name: "Kennel Cough",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["dog"],
    common_symptoms: [6, 7, 36, 29],
  },
  {
    id: 41,
    name: "Feline Upper Respiratory Infection",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [7, 36, 17, 18, 29],
  },
  {
    id: 42,
    name: "Pancreatitis",
    category: "inflammatory",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [1, 25, 3, 4, 32],
  },
  {
    id: 43,
    name: "Bladder Stones",
    category: "urological",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [48, 16, 15, 47],
  },
  {
    id: 44,
    name: "Conjunctivitis",
    category: "inflammatory",
    severity: "low",
    contagious: true,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [17, 18, 19],
  },
  {
    id: 45,
    name: "Inflammatory Bowel Disease",
    category: "inflammatory",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "rabbit", "ferret"],
    common_symptoms: [2, 1, 3, 27, 49],
  },
  {
    id: 46,
    name: "Heartworm Disease",
    category: "parasitic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "ferret"],
    common_symptoms: [6, 5, 4, 32, 27],
  },
  {
    id: 47,
    name: "Luxating Patella",
    category: "orthopedic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat", "rabbit"],
    common_symptoms: [11, 34, 32],
  },
  {
    id: 48,
    name: "Cherry Eye",
    category: "ocular",
    severity: "low",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [18, 17],
  },
  {
    id: 49,
    name: "Bloat (Simple)",
    category: "digestive",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [25, 3, 4, 32],
  },
  {
    id: 50,
    name: "Molar Spurs",
    category: "dental",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [23, 24, 3, 27],
  },
  {
    id: 51,
    name: "Bumblefoot",
    category: "bacterial",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["bird", "rabbit", "guinea_pig"],
    common_symptoms: [11, 45, 44, 34],
  },
  {
    id: 52,
    name: "Egg Binding",
    category: "reproductive",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["bird", "reptile"],
    common_symptoms: [41, 25, 32, 4],
  },
  {
    id: 53,
    name: "Feather Plucking",
    category: "behavioral",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["bird"],
    common_symptoms: [9, 8, 39, 42],
  },
  {
    id: 54,
    name: "Psittacosis",
    category: "bacterial",
    severity: "high",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["bird"],
    common_symptoms: [5, 36, 17, 29, 3],
  },
  {
    id: 55,
    name: "Metabolic Bone Disease",
    category: "metabolic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["reptile", "bird"],
    common_symptoms: [32, 34, 12, 33],
  },
  {
    id: 56,
    name: "Respiratory Infection (Reptile)",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["reptile"],
    common_symptoms: [5, 36, 38, 4],
  },
  {
    id: 57,
    name: "Impaction",
    category: "digestive",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["reptile", "hamster", "guinea_pig"],
    common_symptoms: [26, 25, 3, 4],
  },
  {
    id: 58,
    name: "Shedding Problems",
    category: "dermatological",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["reptile"],
    common_symptoms: [10, 8, 18],
  },
  {
    id: 59,
    name: "Adrenal Disease",
    category: "endocrine",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["ferret"],
    common_symptoms: [9, 3, 32, 25],
  },
  {
    id: 60,
    name: "Insulinoma",
    category: "neoplastic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["ferret"],
    common_symptoms: [32, 4, 33, 13],
  },
  {
    id: 61,
    name: "Dental Abscesses",
    category: "bacterial",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [45, 23, 24, 29],
  },
  {
    id: 62,
    name: "GI Stasis",
    category: "digestive",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [3, 4, 26, 32],
  },
  {
    id: 63,
    name: "Wet Tail",
    category: "bacterial",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["hamster"],
    common_symptoms: [2, 4, 32, 27],
  },
  {
    id: 64,
    name: "Scurvy",
    category: "nutritional",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["guinea_pig"],
    common_symptoms: [12, 44, 22, 32],
  },
  {
    id: 65,
    name: "Ovarian Cysts",
    category: "reproductive",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["guinea_pig"],
    common_symptoms: [9, 25, 32],
  },
  {
    id: 66,
    name: "Myxomatosis",
    category: "viral",
    severity: "critical",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["rabbit"],
    common_symptoms: [45, 17, 18, 29, 4],
  },
  {
    id: 67,
    name: "Rabbit Hemorrhagic Disease",
    category: "viral",
    severity: "critical",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["rabbit"],
    common_symptoms: [4, 5, 36, 29],
  },
  {
    id: 68,
    name: "E. cuniculi",
    category: "parasitic",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["rabbit"],
    common_symptoms: [33, 34, 21, 15],
  },
  {
    id: 69,
    name: "Pasteurellosis",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [7, 36, 17, 29],
  },
  {
    id: 70,
    name: "Tyzzer's Disease",
    category: "bacterial",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["rabbit", "guinea_pig", "hamster"],
    common_symptoms: [2, 4, 32, 29],
  },
  {
    id: 71,
    name: "Cardiomyopathy",
    category: "cardiac",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
    common_symptoms: [5, 35, 32, 4],
  },
  {
    id: 72,
    name: "Lymphoma",
    category: "neoplastic",
    severity: "critical",
    contagious: false,
    zoonotic: false,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
    ],
    common_symptoms: [37, 27, 3, 4],
  },
  {
    id: 73,
    name: "Mast Cell Tumors",
    category: "neoplastic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [43, 8, 45, 1],
  },
  {
    id: 74,
    name: "Intervertebral Disc Disease",
    category: "orthopedic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog"],
    common_symptoms: [11, 34, 32, 33],
  },
  {
    id: 75,
    name: "Cruciate Ligament Injury",
    category: "orthopedic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [11, 34, 12, 32],
  },
  {
    id: 76,
    name: "Progressive Retinal Atrophy",
    category: "genetic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [19, 34],
  },
  {
    id: 77,
    name: "Addison's Disease",
    category: "endocrine",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog"],
    common_symptoms: [32, 1, 2, 4],
  },
  {
    id: 78,
    name: "Cushing's Disease",
    category: "endocrine",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["dog", "cat"],
    common_symptoms: [14, 15, 28, 9],
  },
  {
    id: 79,
    name: "Feline Asthma",
    category: "respiratory",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [6, 5, 35],
  },
  {
    id: 80,
    name: "Hypertrophic Cardiomyopathy",
    category: "cardiac",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [5, 35, 32, 31],
  },
  {
    id: 81,
    name: "Feline Lower Urinary Tract Disease",
    category: "urological",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["cat"],
    common_symptoms: [48, 15, 16, 47],
  },
  {
    id: 82,
    name: "Bovine Respiratory Disease",
    category: "respiratory",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["cow"],
    common_symptoms: [6, 36, 29, 5],
  },
  {
    id: 83,
    name: "Johne's Disease",
    category: "bacterial",
    severity: "high",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["cow", "goat", "sheep"],
    common_symptoms: [2, 27, 3, 32],
  },
  {
    id: 84,
    name: "Pregnancy Toxemia",
    category: "metabolic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["goat", "sheep"],
    common_symptoms: [32, 3, 4, 13],
  },
  {
    id: 85,
    name: "Caseous Lymphadenitis",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["goat", "sheep"],
    common_symptoms: [37, 43, 44],
  },
  {
    id: 86,
    name: "Caprine Arthritis Encephalitis",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["goat"],
    common_symptoms: [10, 12, 32, 13],
  },
  {
    id: 87,
    name: "Ovine Progressive Pneumonia",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["sheep"],
    common_symptoms: [5, 6, 27, 32],
  },
  {
    id: 88,
    name: "Enterotoxemia",
    category: "bacterial",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["goat", "sheep"],
    common_symptoms: [2, 25, 13, 32],
  },
  {
    id: 89,
    name: "Equine Influenza",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["horse"],
    common_symptoms: [6, 29, 36, 4],
  },
  {
    id: 90,
    name: "Strangles",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["horse"],
    common_symptoms: [37, 29, 36, 50],
  },
  {
    id: 91,
    name: "Equine Protozoal Myeloencephalitis",
    category: "parasitic",
    severity: "high",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["horse"],
    common_symptoms: [34, 32, 33, 11],
  },
  {
    id: 92,
    name: "Heaves (RAO)",
    category: "respiratory",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["horse"],
    common_symptoms: [6, 5, 35, 36],
  },
  {
    id: 93,
    name: "Navicular Disease",
    category: "orthopedic",
    severity: "medium",
    contagious: false,
    zoonotic: false,
    applicable_animals: ["horse"],
    common_symptoms: [11, 34],
  },
  {
    id: 94,
    name: "Porcine Reproductive and Respiratory Syndrome",
    category: "viral",
    severity: "high",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["pig"],
    common_symptoms: [5, 6, 29, 52],
  },
  {
    id: 95,
    name: "Swine Flu",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["pig"],
    common_symptoms: [6, 29, 36, 4],
  },
  {
    id: 96,
    name: "African Swine Fever",
    category: "viral",
    severity: "critical",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["pig"],
    common_symptoms: [29, 10, 44, 4],
  },
  {
    id: 97,
    name: "Erysipelas",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: ["pig"],
    common_symptoms: [10, 29, 12, 11],
  },
  {
    id: 98,
    name: "Porcine Circovirus",
    category: "viral",
    severity: "medium",
    contagious: true,
    zoonotic: false,
    applicable_animals: ["pig"],
    common_symptoms: [27, 32, 2, 10],
  },
  {
    id: 99,
    name: "Salmonellosis",
    category: "bacterial",
    severity: "high",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "reptile",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [2, 1, 29, 4, 32],
  },
  {
    id: 100,
    name: "Campylobacteriosis",
    category: "bacterial",
    severity: "medium",
    contagious: true,
    zoonotic: true,
    applicable_animals: [
      "dog",
      "cat",
      "rabbit",
      "guinea_pig",
      "hamster",
      "ferret",
      "bird",
      "cow",
      "goat",
      "sheep",
      "horse",
      "pig",
    ],
    common_symptoms: [2, 1, 29, 25],
  },
];
